### ISSUE TITLE
OF applications that use ofxFaceTracker2 crash because of the path to the predictor

### ISSUE THREAD

**Issue by orgicus** [ml4a/ml4a-ofx#7]
To use the ofxFaceTracker 2 examples at the moment I followed these steps:

1. Downloaded [shape_predictor_68_face_landmarks.dat.bz2](http://sourceforge.net/projects/dclib/files/dlib/v18.10/shape_predictor_68_face_landmarks.dat.bz2)
2. Unzipped it to `YOUR_OF_FOLDER/addons/ofxFaceTracker2/model`

After that ofxFaceTracker2 examples worked.

At the moment, all the examples that have this line:

`../../../../data/shape_predictor_68_face_landmarks.dat`
which should change to this:
`../../../data/shape_predictor_68_face_landmarks.dat`

Also copy the .dat file to the app's data folder(e.g. FaceClassifier/bin/data). 

Another option is to symlink the .dat file.

**Comment by genekogan** [comment]
we wanted to place all the large data files for ofxFaceTracker2 and ofxCcv so that you could keep them in one place (with respect to ml4a-ofx) instead of copying them into every folder. if you have `shape_predictor_68_face_landmarks.dat` inside `ml4a-ofx/data` then the original path (../../../../) should work fine for any app in ml4a-ofx that uses it.
